name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
<<<<<<< HEAD
      - run: flutter build web --release
        working-directory: . /flutter_page/lib/main.dart
      - run: 
          cd ./flutter_page/build/web
=======
      - run: flutter build web --
        working-directory: ./lib/main.dart
      - run: 
          cd ./build/web
>>>>>>> 684a448c00ae5ae47192b0645231eddb378a6df2
          git init
          git config --global user.email limemoon@kakao.com
          git config --global user.name LimeMoon
          git status
          git remote add origin https://github.com/LimeFlavoredMoon/LimeFlavoredMoon.github.io 
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
<<<<<<< HEAD
          git push origin gh-pages -f
=======
          git push origin gh-pages -f
>>>>>>> 684a448c00ae5ae47192b0645231eddb378a6df2
